services:
  mariadb:
    container_name: mariadb-credit-api
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: creditDb
      MARIADB_USER: mariadb_user
      MARIADB_PASSWORD: mariadb_password
    ports:
      - "3316:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./seata-client-config/mysql.sql:/docker-entrypoint-initdb.d/seata.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mysql_user", "-pmysql_password" ]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true

volumes:
  mariadb_data:
